### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by minnypatel** [cmharrison-astro/esoscienceambassadors#19]
https://support.google.com/analytics/answer/1008080?hl=en
https://support.google.com/analytics/answer/1042508

**Comment by minnypatel** [comment]
In retrospect, we'll need the website name and URL to get any further with this.
@cmharrison-astro let me know when you've got them, in the meantime I'll move this card back to the backlog.


<img width="508" alt="screen shot 2018-09-04 at 12 57 31" src="https://user-images.githubusercontent.com/6986623/45029958-377bf200-b042-11e8-8272-d15dd8af0a0e.png">

**Comment by cmharrison-astro** [comment]
http://www.biggesteyeonthesky.org

One thing I managed to do was purchase some space and the domain name. Trouble is I can't access it at the moment because I am outside of the UK...well I need to ring the hosting company to sort that. 

Today I submitted the big fellowship application that I was trying to get done so I should have some more time to make progress...although I am currently at conference,

**Comment by minnypatel** [comment]
No problem. I'm currently pretty busy too! 

You okay for me to put "Biggest Eye On The Sky" as the website name?

**Comment by cmharrison-astro** [comment]
Yes, that name works
